name: Deploy to AWS Lightsail

# 임시로 비활성화 - secrets 설정 후 다시 활성화
on:
  workflow_dispatch:  # 수동 실행만 가능
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd ~/newsletter-app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python init_db.py
          sudo systemctl restart newsletter
          sudo systemctl restart nginx 